### ISSUE TITLE
Create a storage reason collection

### ISSUE THREAD

**Issue by moshemalawach** [aleph-im/pyaleph#104]
To avoid the attack vector where a user can ask for a FORGET or set an expiry time on a hash he doesn't own, we need to store a collections that matches hashes with the reasons for which we need to keep them.

**Comment by moshemalawach** [comment]
Proposed collection structure:

- hash
- engine (storage, ipfs)
- source (temporary, sync, message_content, store, virtual_machine)
- ref (reference to the original content, depends on the source... typically for sync it will be the tx hash, for message_content and store it needs to reference these: item_hash -implied in message_content as it's the current hash-, message_type, sender, chain)
- size
- content_type (file, json, folder...)

**Comment by hoh** [comment]
Fixed in 8b209b9e3d2e64c17d22c44ba2f41b0bb64f7dfb
