### ISSUE TITLE
Support search by key in messages.json API endpoint

### ISSUE THREAD

**Issue by moshemalawach** [aleph-im/pyaleph#156]
The messages.json api endpoint should support a "keys" param that searches in "content.key".

The change should be done in src/aleph/web/controllers/messages.py both in KNOWN_QUERY_FIELDS and get_filters

**Comment by odesenfans** [comment]
Is this what you need? https://github.com/aleph-im/pyaleph/pull/157

I pointed it to the dev branch but I can point to `master` if you prefer.

**Comment by odesenfans** [comment]
Resolved by #157.
