### ISSUE TITLE
Missing startDate and endDate in KNOWN_QUERY_FIELDS

### ISSUE THREAD

**Issue by geraldinefiser** [aleph-im/pyaleph#158]
I think the KNOWN_QUERY_FIELDS is missing the "time" query params startDate and endDate that would be passed from the get_messages function of the SDKs. 

https://github.com/aleph-im/pyaleph/blob/878f7a3026c8ad9fc722cc2e9b65fc938fe65ae6/src/aleph/web/controllers/messages.py#L15

**Comment by odesenfans** [comment]
We could easily add those, however I don't see them in the [JS SDK](https://github.com/aleph-im/aleph-js/blob/master/src/api/messages.js). Could you link the reference to the client code that uses these parameters?

**Comment by odesenfans** [comment]
Resolved by #166.
