### ISSUE TITLE
Message signature verification fails silently

### ISSUE THREAD

**Issue by odesenfans** [aleph-im/pyaleph#163]
The (verification of the signature of the message)[https://github.com/aleph-im/pyaleph/blob/878f7a3026c8ad9fc722cc2e9b65fc938fe65ae6/src/aleph/network.py#L130] fails silently. The `check_message` function then returns a null value which results in an exception later down the line.

What's the expected behavior? Ignore the message if the signature is not verified? Log this event somewhere?

**Comment by odesenfans** [comment]
Resolved by #164.

**Comment by moshemalawach** [comment]
The issue is that producing a huge amount of bad messages with forged signatures can be an attack vector. Hence the silent fail and message ignore if the signature is bad...

**Comment by odesenfans** [comment]
Here it was more about the function checking the signature that was returning `None` implicitly, which is not great. With the fix in #164 the function raises an `InvalidMessageError` instead, which is then caught by the caller who proceeds to ignore the message. The behavior is the same as before.
