### ISSUE TITLE
P2P daemon "control port" is exposed to the internet

### ISSUE THREAD

**Issue by hoh** [aleph-im/pyaleph#169]
The `p2pd` section of the new docker-compose exposes port 4020 to the internet. Is that by design ?

https://github.com/aleph-im/pyaleph/blob/dev/deployment/docker-compose/docker-compose.yml#L43

**Comment by odesenfans** [comment]
That's not wanted, I'll fix it right away.

**Comment by odesenfans** [comment]
Resolved by #170.
