### ISSUE TITLE
Dependency conflicts

### ISSUE THREAD

**Issue by hoh** [aleph-im/pyaleph#17]
Multiple dependencies of `pyaleph` have conflicts.

This issue aims at tracking and solving these issues.

- [ ] `base58` version conflict between `aleph-im/py-libp2p` and `py-substrate-interface` - Pull Request: https://github.com/aleph-im/py-libp2p/pull/1
- [ ] `neo-python` is not compatible with `pip>=20` - This is fixed in their `development` branch, commit https://github.com/CityOfZion/neo-python/commit/96b01ef09a04991293a9bcea32ab25b25bd82891

**Comment by moshemalawach** [comment]
Thanks!
Accepted the PR.
As for neo-python, we can deprecate NEO support altogether. It will need removals in:
- aleph-client
- aleph-js
- pyaleph

**Comment by hoh** [comment]
- [ ] two1-python has old frozen dependencies - See https://github.com/21dotco/two1-python/issues/29. 

The maintainer of that repository does not appear to react. What about hosting a fork on https://github.com/aleph-im/two1-python that releases that constraint ?

**Comment by moshemalawach** [comment]
We will remove it as well, it's used by python binance chain and we can use raw rest calls using aiohttp and cosmospy to pack transactions. Would need a new feature "generic cosmos sdk" support on sync side (it's there for the message verification already).
