### ISSUE TITLE
Very high usage of container PyAleph since v0.2.0 from file `/tmp/messages_task_loop.log`

### ISSUE THREAD

**Issue by hoh** [aleph-im/pyaleph#211]
Reported by Tg users `aiz` and `Arimav`, reproduced by @hoh .

`/var/lib/docker/overlay2` increases sharply to more than a hundred GB.

The easiest fix in production is to restart the pyaleph container.
```
docker-compose down
docker-compose up
```

> Executing `truncate -s 0 /tmp/messages_task_loop.log` inside the container raises the error `truncate: cannot open '/tmp/messages_task_loop.log' for writing: Permission denied`

The issue comes from verbose logging of a PyAleph process.
It may be the case that this logging setup ignores the default logging level (WARNING) and still writes DEBUG level logs.

**Comment by odesenfans** [comment]
After investigation, setting the log level on the CLI works as expected. The log level is correctly propagated to the subprocesses. The only configuration in which this is not true is if the user specifies:

```
logging:
    level: 10
```
in his config.yml file, apparently this overrides the CLI value for subprocesses. It should not, I will propose a fix.

Besides that, I'll change the default log level to INFO in the Docker Compose files.
