### ISSUE TITLE
[FEATURE REQUEST] Amending someone else's POST

### ISSUE THREAD

**Issue by Blizzsuxx** [aleph-im/pyaleph#239]
Say you have an app built around Aleph that has users and administrators.
Users can only register by submitting a request (via submitting a POST message) to the administrators to make them an account.
The administrators can view the requests, and can choose to approve (resulting in another POST message by the administrator, this one creating an account) or reject (no output) the request.
The issue here is that whenever the administrator would boot up the app, he would receive the same requests/messages he had rejected / accepted.
Ideal solution: amending the post of the user adding a flag that could be used to filter out already read requests/messages.

**Comment by odesenfans** [comment]
Hi @Blizzsuxx, thanks for the request. As mentioned on Telegram we are working on a delegation mechanism. It's on the roadmap for later this year.
