### ISSUE TITLE
Add support for trusted messages from Tezos

### ISSUE THREAD

**Issue by hoh** [aleph-im/pyaleph#240]
Messages from Tezos do not have a signature since they come directly from a chain. This should be supported by PyAleph and Aleph-Message.

**Comment by odesenfans** [comment]
Do you have a concrete example of such a message on Tezos? Is there no way to validate the authenticity of the message at all? Also, if we don't have a signature, how are we supposed to check the balance of the user if the message contains a billable action?

**Comment by odesenfans** [comment]
Added in v0.4.4.
