### ISSUE TITLE
Faster JSON using orjson ?

### ISSUE THREAD

**Issue by hoh** [aleph-im/pyaleph#297]
https://pypi.org/project/orjson/

> orjson is a fast, correct JSON library for Python. It [benchmarks](https://github.com/ijl/orjson#performance) as the fastest Python library for JSON and is more correct than the standard json library or other third-party libraries. It serializes [dataclass](https://github.com/ijl/orjson#dataclass), [datetime](https://github.com/ijl/orjson#datetime), [numpy](https://github.com/ijl/orjson#numpy), and [UUID](https://github.com/ijl/orjson#uuid) instances natively.

**Comment by odesenfans** [comment]
`orjson` looks promising, but we'd need to check how well it plays with Pydantic models. At the moment, JSON serialization/deserialization is not identified as a performance issue though, so no rush in investigating this.

**Comment by odesenfans** [comment]
Integrated with the work on Postgres.
