### ISSUE TITLE
Avalanche messages have a unique digest prefix

### ISSUE THREAD

**Issue by BjrInt** [aleph-im/pyaleph#310]
Is there a rational behind this decision? It is the only supported Chain to have one. 

https://github.com/aleph-im/pyaleph/blob/3b858482995c73b21f17faed93abc240a7ef004c/src/aleph/chains/avalanche.py#L15

See also : https://github.com/aleph-im/aleph-sdk-ts/pull/20#discussion_r942262049

**Comment by hoh** [comment]
@moshemalawach any idea ?
