### ISSUE TITLE
Websocket filters are not working

### ISSUE THREAD

**Issue by BjrInt** [aleph-im/pyaleph#369]
# Problem description

None of the query parameters passed to the websocket URL seem to work. ex: `wss://api2.aleph.im/api/ws0/messages?msgType=POST` will return the last messages regardless of their types. It's the same for every other filters available (at least using the syntax advertised [here](https://aleph-im.gitbook.io/ts-sdk/guides/websockets)).

*Could be a documentation issue.

**Comment by odesenfans** [comment]
Have you tried on the Postgres test server (163)? I think I fixed that one.

**Comment by BjrInt** [comment]
Yes! It works on the postgres instance. :+1:
