### ISSUE TITLE
Update libp2p to version 0.1.4 ?

### ISSUE THREAD

**Issue by hoh** [aleph-im/pyaleph#47]
I tested libp2p version 0.1.4 (before [the switch to trio](https://github.com/libp2p/py-libp2p/releases/tag/v0.1.5)) and it seems to work, but I am not aware of how to test it properly.

If that appears to work, should we switch to that code, or merge it with the changes done in [aleph-im/py-libp2p](https://github.com/aleph-im/py-libp2p) ?

My branch is hoh-upgrade-libp2p ([diff](https://github.com/aleph-im/pyaleph/compare/hoh-upgrade-libp2p)).

**Comment by olethanh** [comment]
Modification in py-libp2p https://github.com/aleph-im/py-libp2p/pull/3/files

**Comment by hoh** [comment]
Analyser les tests unitaires de la librairie ainsi que l'éventualité de fuites mémoire.
