### ISSUE TITLE
Docker requires re-downloading all Pypi dependencies on any source code change

### ISSUE THREAD

**Issue by hoh** [aleph-im/pyaleph#53]
The Docker images install Python dependencies using the `setup.cfg` file by running `pip install -e ".[nuls2,testing]"`.

Since this command is run after copying the source code of pyaleph in the image, any change in the source code invalidates the Docker cache containing the installation of the Python dependencies and requires downloading them again from Pypi. This may cause build systems to reach the Pypi Rate Limiting.

**Comment by odesenfans** [comment]
Should be fixed by #139 .

**Comment by odesenfans** [comment]
Resolved by #139.
