### ISSUE TITLE
Can't run docker-compose with version: "2.4" in docker-compose.yaml

### ISSUE THREAD

**Issue by rshellnet** [aleph-im/pyaleph#54]
When trying to run, getting an error:

#docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the services key, or omit the version key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

Changed version to "2.2", everything runs ok.

**Comment by hoh** [comment]
This was reported when using Ubuntu 18.04.5 LTS.

**Comment by cryptarchnoble** [comment]
Also received this, using Ubuntu 18.04.5 LTS (Bionic Beaver), docker-compose version 1.17.1, build unknown. Modifying the compose file and changing the version to "2.2" worked for me as well.
