### ISSUE TITLE
Python `requirements.txt` creates confusion as it is not up-to-date

### ISSUE THREAD

**Issue by hoh** [aleph-im/pyaleph#70]
Python dependencies are installed from [setup.cfg](setup.cfg) and not from [requirements.txt](requirements.txt).

This is confusing as [requirements.txt](requirements.txt) is expected to be the way to go by some Python developers and tutorials, but will not work since it is not updated.

Proposals, either:
- Remove `requirements.txt` from the repository
- Ensure it is up-to-date with CI

**Comment by odesenfans** [comment]
Removed the requirements file in #138 .

**Comment by odesenfans** [comment]
Actually fixed by #151 .
