### ISSUE TITLE
Python processes use more and more memory over time (memory leak)

### ISSUE THREAD

**Issue by hoh** [aleph-im/pyaleph#71]

**Comment by hoh** [comment]
Commit c1bc0df4a25cb3be408fb7b46620377d6322d4db now gives us much more visibility on this topic, especially when combined with Prometheus and Grafana to visualise the evolution of the system.

**Comment by hoh** [comment]
Reducing the threshold `if (j >= 20000):` to 2000 in `src/aleph/jobs.py` seems to reduce the memory used a lot.

**Comment by odesenfans** [comment]
The memory usage of the message processing job is now stable, albeit a bit high for what it is. There is still a memory leak within the P2P daemon but that's another issue entirely. Closing this one.
