### ISSUE TITLE
Handle STORE message type

### ISSUE THREAD

**Issue by moshemalawach** [aleph-im/pyaleph#9]
The address is typically in the message content, do we:
- move the "address" for which this message is for (paying?) in the root message itself
- or do we force those messages to be for self
- add a content (forcing it to be inline) like this: {'address': 'XX', 'file': 'XX', 'item_type': 'XX'} (only allowed 'ipfs' and 'storage')

On the two first options for the content we use the regular content fetching system (but it might be in-adapted since it's not json and it might bork older implementations, making it a backward incompatible move)

**Comment by moshemalawach** [comment]
Having a content with an address key allows to stay in the regular authorization/permission process for storage, let's go this way (3rd).

**Comment by odesenfans** [comment]
STORE messages are supported, I think we can safely close this issue.
